export const FETCH_ENDPOINT_DATA_SUCCESS = 'FETCH_ENDPOINT_DATA_SUCCESS';
export const FETCH_ENDPOINT_DATA_ERROR = 'FETCH_ENDPOINT_DATA_ERROR';
export const PUSH_ENDPOINT = 'PUSH_ENDPOINT';
export const UPDATE_HOVER_ENDPOINT = 'UPDATE_HOVER_ENDPOINT';
export const UPDATE_PAGE = 'UPDATE_PAGE';